project:
  name: Loan Default Risk Prediction
  version: 1.0

data:
  raw_data_path: data/raw/application_train.csv

  train_path: data/interim/train.csv

  test_path: data/interim/test.csv

  target_column: TARGET

model:
  random_state: 42

  test_size: 0.20